### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yuta8995** [yuta8995/furima-34750#9]
# 自身のフリマアプリのURL
https://furima-34750.herokuapp.com/

# Basic認証のIDとパスワード
ID: admin　パスワード: 2222

# 出品者用のメールアドレスとパスワード
メールアドレス: tanaka@gmail.com　パスワード: 111aaa

# 購入者用のメールアドレスとパスワード
メールアドレス: nishikawa@gmail.com　パスワード: 111aaa

**Comment by takumi0530** [comment]
@yuta8995 さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **エラーハンドリングの際、1つのエラーに対して同じエラーメッセージが重複して表示されないこと（出品・編集）**
「Price can't be blank」の文字が重複しています。
<img width="225" alt="スクリーンショット 2021-07-21 10 52 04" src="https://user-images.githubusercontent.com/76197191/126418174-2c613833-5b64-470c-a582-840171f68418.png">

- [x] **「画像/価格/商品名/配送料負担」の4つの情報について表示できていること**
配送料負担の部分が数字になってしまっています。
<img width="324" alt="スクリーンショット 2021-07-21 10 53 51" src="https://user-images.githubusercontent.com/76197191/126418253-93968e79-579a-431d-81ce-8e842e805d4e.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@yuta8995 さん、再度ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/126423878-245432a7-32b7-4810-8d14-061af1be5f6c.png)
